### ISSUE TITLE
Look for "python3" as well. 

### ISSUE THREAD

**Issue by duckartes** [notthebee/macos_usb#11]
First of all, thanks for the script, saved the day. 

I had to modify the script to serach for "python3" as Pop_OS! does not hae "python" installed by default. 

It would also be useful if the script would separate different versions in to different folders and ask to utilize previously downloaded files (I have slow metered hotspot) or to start fresh.

**Comment by junx404** [comment]
What did you change to make it search for python3? Need the script but i can't run it anymore. Would be very happy if you could share :)
